### ISSUE TITLE
Popups should persist through the user zooming

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#31]

**Comment by abartow** [comment]
This might be tricky due to moving the tooltip during zoom. The way to deal with that may be to always have the popups emirate from the center of the table, and then use panzoom's [onPan/onZoom events ](https://github.com/timmywil/jquery.panzoom) to recalculate the center of the table. 

We probably also want to make them persist through panning then?

**Comment by abartow** [comment]
Should be done as of https://github.com/ZackUhlenhuth/HostHelper/commit/f1c7ad3a98a918efbbe8690a9d22191f52736bfc
